# -*- coding: utf-8 -*-
"""Day 4 and 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/vanshch123/day-4-and-5.53fde7f9-473b-4ad1-8c9e-39654bbaae71.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20260129/auto/storage/goog4_request%26X-Goog-Date%3D20260129T185218Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D4f6b3496567fb97208784e87e8823d0175865a7fd9f5265b0478a0ff544b9c09e4ac89c14cb20586a84d7dd9753d5c463830568ff07a4fae8c38e052fee7d9a130396dc1ea670c2c641c894a885727f598ca9f2440edcde42aba896376bcf5c89f31e4505fc61f6b27399e9e8165f5a1f1185798d91c55bb6325e9035b75aa5ccada73019afac63dad8019be7f6299ee54b6b82af709be035a50f783e8bb0471adabdb02ca492b400e15e2a100219a372f4e6e2780e58f5437e1f5b8b4e8b62d271dfe63eb036c49c68184cb6b70d837f597024745fe2ad5a3899c5532d246abdca1031339101dcc18a441c4474ac8ccdb354c19ff06c1d3cf3268303b683c2b
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
nikhil1e9_loan_default_path = kagglehub.dataset_download('nikhil1e9/loan-default')

print('Data source import complete.')

import pandas as pd
df = pd.read_csv('/kaggle/input/loan-default/Loan_default.csv')
df = df.drop(['LoanID'],axis = 1)

"""# ML flow setup"""

!pip install mlflow -qqq

import mlflow

mlflow.set_tracking_uri("file:/kaggle/working/mlruns")
mlflow.set_experiment("my_experiment")

"""# Missing values imputation/dropping
- Since no missing values no need to complete this
"""

df.info()

"""## Feature Classification
- Numeric (scaled): Large-range continuous financial variables
- Numeric (unscaled): Bounded or count-based variables
- Ordinal categorical: Ordered categories
- Nominal categorical: Unordered categories
- Binary categorical: Explicit 0/1 mapping

# train test split
"""

from sklearn.model_selection import train_test_split
X = df.drop('Default',axis = 1)
y = df['Default']
X_train,X_test,y_train,y_test= train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify=True,
    shuffle = True
)

num_unscaled = [
    "Age",
    "MonthsEmployed",
    "NumCreditLines",
    "LoanTerm"
]

num_scaled = [
    "Income",
    "LoanAmount",
    "CreditScore",
    "InterestRate",
    "DTIRatio"
]

ordinal_cols = [
    "Education"
]
nominal_cols = [
    "EmploymentType",
    "MaritalStatus",
    "LoanPurpose"
]
binary_cols = [
    "HasMortgage",
    "HasDependents",
    "HasCoSigner"
]

"""- Numeric scaling is applied to num_scaled where numeric stability is important.
- Ordinal categories are encoded with ordering.
- Nominal categories are one-hot encoded without dropping reference categories.
- Binary features are mapped directly to 0/1 for clarity.

"""

from sklearn.preprocessing import OrdinalEncoder

education_order = [
    ["High School", "Bachelor's", "Master's", "PhD"]
]

ordinal_encoder = OrdinalEncoder(categories=education_order)

binary_encoder = OrdinalEncoder(
    categories=[['No','Yes']] * 3 # No -> 0 and yes -> 1
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("num_scaled", StandardScaler(), num_scaled),
        ("binary",binary_encoder, binary_cols),
        ("num_unscaled", "passthrough", num_unscaled),
        ("ordinal", ordinal_encoder, ordinal_cols),
        ("nominal", OneHotEncoder(handle_unknown="ignore", sparse_output=False,drop='first'), nominal_cols),
    ],
    remainder="drop",
    # verbose=True
)

preprocessor_tree = ColumnTransformer(
    transformers=[
        ("num_scaled", "passthrough", num_scaled),
        ("num_unscaled", "passthrough", num_unscaled),
        ("binary",binary_encoder, binary_cols),
        ("ordinal", ordinal_encoder, ordinal_cols),
        ("nominal", OneHotEncoder(handle_unknown="ignore", sparse_output=False), nominal_cols),
    ],
    remainder="drop",
    # verbose=True
)

import mlflow
import mlflow.sklearn

from sklearn.metrics import roc_auc_score
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
with mlflow.start_run():
    pipe = Pipeline(
        steps=[
            ("preprocess", preprocessor),
            ("model", LogisticRegression(
                max_iter=1000,
                solver="lbfgs",
                n_jobs=-1
            ))
        ]
    )

    cv_scores = cross_val_score(
        pipe,
        X_train,
        y_train,
        cv=5,
        scoring="roc_auc"
    )
    pipe.fit(X_train,y_train)

    mlflow.log_metric("cv_roc_auc_mean", cv_scores.mean())
    mlflow.log_metric("cv_roc_auc_std", cv_scores.std())

    y_test_proba = pipe.predict_proba(X_test)[:, 1]

    test_roc_auc = roc_auc_score(y_test, y_test_proba)

    mlflow.log_metric("test_roc_auc", test_roc_auc)

    mlflow.sklearn.log_model(
        pipe,
        artifact_path="model"
    )


    print("CV ROC-AUC scores:", cv_scores)
    print("Mean ROC-AUC:", cv_scores.mean())
    print("test_roc_auc", test_roc_auc)

from sklearn.metrics import (
    precision_score, recall_score, f1_score,
    accuracy_score, confusion_matrix
)
import pandas as pd

y_test_pred = (y_test_proba >= 0.5).astype(int)

mlflow.log_metric("test_precision", precision_score(y_test, y_test_pred))
mlflow.log_metric("test_recall", recall_score(y_test, y_test_pred))
mlflow.log_metric("test_f1", f1_score(y_test, y_test_pred))
mlflow.log_metric("test_accuracy", accuracy_score(y_test, y_test_pred))

# Confusion matrix as artifact
cm = confusion_matrix(y_test, y_test_pred)
cm_df = pd.DataFrame(cm, index=["Actual_0", "Actual_1"], columns=["Pred_0", "Pred_1"])
cm_df.to_csv("confusion_matrix.csv", index=True)

mlflow.log_artifact("confusion_matrix.csv")

print("test_roc_auc", test_roc_auc)

"""# Day 5"""

mlflow.end_run()

import mlflow
import mlflow.sklearn
import mlflow.lightgbm
import mlflow.xgboost

from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score
import pandas as pd
import lightgbm as lgb
import xgboost as xgb

with mlflow.start_run(run_name="Pipeline_LightGBM"):

    pipe_lgb = Pipeline(
        steps=[
            ("preprocess",preprocessor_tree ),
            ("model", lgb.LGBMClassifier(
                n_estimators=500,
                learning_rate=0.05,
                max_depth=-1,
                num_leaves=31,
                subsample=0.8,
                colsample_bytree=0.8,
                objective="binary",
                random_state=42
            ))
        ]
    )

    pipe_lgb.fit(X_train, y_train)

    y_train_proba = pipe_lgb.predict_proba(X_train)[:, 1]
    y_test_proba = pipe_lgb.predict_proba(X_test)[:, 1]

    train_auc = roc_auc_score(y_train, y_train_proba)
    test_auc = roc_auc_score(y_test, y_test_proba)

    # ---- MLflow logging ----
    mlflow.log_params(pipe_lgb.named_steps["model"].get_params())
    mlflow.log_metric("train_roc_auc", train_auc)
    mlflow.log_metric("test_roc_auc", test_auc)

    mlflow.sklearn.log_model(pipe_lgb, artifact_path="model")

    # ---- Feature importance (post-preprocessing) ----
    feature_names = pipe_lgb.named_steps["preprocess"].get_feature_names_out()

    fi = pd.DataFrame({
        "feature": feature_names,
        "importance": pipe_lgb.named_steps["model"].feature_importances_
    }).sort_values("importance", ascending=False)

    fi.to_csv("lgb_feature_importance.csv", index=False)
    mlflow.log_artifact("lgb_feature_importance.csv")

    print("LightGBM Train ROC-AUC:", train_auc)
    print("LightGBM Test ROC-AUC:", test_auc)
    print(fi.head(10))

with mlflow.start_run(run_name="Pipeline_XGBoost"):

    pipe_xgb = Pipeline(
        steps=[
            ("preprocess", preprocessor),
            ("model", xgb.XGBClassifier(
                n_estimators=500,
                learning_rate=0.05,
                max_depth=6,
                subsample=0.8,
                colsample_bytree=0.8,
                objective="binary:logistic",
                eval_metric="auc",
                random_state=42
            ))
        ]
    )

    pipe_xgb.fit(X_train, y_train)

    y_train_proba = pipe_xgb.predict_proba(X_train)[:, 1]
    y_test_proba = pipe_xgb.predict_proba(X_test)[:, 1]

    train_auc = roc_auc_score(y_train, y_train_proba)
    test_auc = roc_auc_score(y_test, y_test_proba)

    # ---- MLflow logging ----
    mlflow.log_params(pipe_xgb.named_steps["model"].get_params())
    mlflow.log_metric("train_roc_auc", train_auc)
    mlflow.log_metric("test_roc_auc", test_auc)

    mlflow.sklearn.log_model(pipe_xgb, artifact_path="model")

    # ---- Feature importance ----
    feature_names = pipe_xgb.named_steps["preprocess"].get_feature_names_out()

    fi = pd.DataFrame({
        "feature": feature_names,
        "importance": pipe_xgb.named_steps["model"].feature_importances_
    }).sort_values("importance", ascending=False)

    fi.to_csv("xgb_feature_importance.csv", index=False)
    mlflow.log_artifact("xgb_feature_importance.csv")

    print("XGBoost Train ROC-AUC:", train_auc)
    print("XGBoost Test ROC-AUC:", test_auc)
    print(fi.head(10))

"""# Downloading MLflow file in zip"""

! cd /kaggle/working ; zip -r mlruns.zip mlruns -q

